In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,classification_report,mean_squared_error,accuracy_score
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df=pd.read_csv('Downloads/play_tennis.csv')

In [3]:
df.head()

day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [6]:
for i in df.columns:
    print(type(i))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [4]:
df.isna().sum()

day         0
outlook     0
temp        0
humidity    0
wind        0
play        0
dtype: int64

In [5]:
le=LabelEncoder()

In [6]:
for col in ['day','outlook','temp','humidity','wind']:
    df[col]=le.fit_transform(df[col])

In [7]:
df.drop('day',axis=1,inplace=True)

In [8]:
df['play']=le.fit_transform(df.play)

In [9]:
df

outlook  temp  humidity  wind  play
0         2     1         0     1     0
1         2     1         0     0     0
2         0     1         0     1     1
3         1     2         0     1     1
4         1     0         1     1     1
5         1     0         1     0     0
6         0     0         1     0     1
7         2     2         0     1     0
8         2     0         1     1     1
9         1     2         1     1     1
10        2     2         1     0     1
11        0     2         0     0     1
12        0     1         1     1     1
13        1     2         0     0     0

In [10]:
x_train,x_test,y_train,y_test=train_test_split(df.drop('play',axis=1),df.play,random_state=101,test_size=0.2)

In [11]:
gb=GaussianNB()

In [12]:
gb.fit(x_train,y_train)

GaussianNB()

In [13]:
y_pred=gb.predict(x_test)

In [14]:
y_test

12    1
2     1
3     1
Name: play, dtype: int64

In [15]:
y_pred

array([1, 1, 0])

In [16]:
accuracy_score(y_pred,y_test)

0.6666666666666666

In [17]:
confusion_matrix(y_pred,y_test)

array([[0, 1],
       [0, 2]])

Titanic dataset

In [18]:
tit_df=pd.read_csv('Downloads/tested.csv')

In [19]:
tit_df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [20]:
tit_df.select_dtypes(include=['object'])

Name     Sex              Ticket  \
0                                Kelly, Mr. James    male              330911   
1                Wilkes, Mrs. James (Ellen Needs)  female              363272   
2                       Myles, Mr. Thomas Francis    male              240276   
3                                Wirz, Mr. Albert    male              315154   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female             3101298   
..                                            ...     ...                 ...   
413                            Spector, Mr. Woolf    male           A.5. 3236   
414                  Oliva y Ocana, Dona. Fermina  female            PC 17758   
415                  Saether, Mr. Simon Sivertsen    male  SOTON/O.Q. 3101262   
416                           Ware, Mr. Frederick    male              359309   
417                      Peter, Master. Michael J    male                2668   

    Cabin Embarked  
0     NaN        Q  
1     NaN        S  
2     NaN        Q  
3     NaN        S  
4     NaN        S  
..    ...      ...  
413   NaN        S  
414  C105        C  
415   NaN        S  
416   NaN        S  
417   NaN        C  

[418 rows x 5 columns]

In [21]:
tit_df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [22]:
tit_df.drop(['Name','PassengerId','Cabin','Ticket'],axis=1,inplace=True)

In [23]:
for col in ['Sex','Embarked']:
    tit_df[col]=le.fit_transform(tit_df[col])

In [24]:
tit_df.isna().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [25]:
tit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  418 non-null    int64  
 1   Pclass    418 non-null    int64  
 2   Sex       418 non-null    int64  
 3   Age       332 non-null    float64
 4   SibSp     418 non-null    int64  
 5   Parch     418 non-null    int64  
 6   Fare      417 non-null    float64
 7   Embarked  418 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 26.2 KB


In [26]:
tit_df['Age'].fillna(np.mean(tit_df['Age']),inplace=True)

In [27]:
tit_df.Fare.fillna(np.mean(tit_df['Fare']),inplace=True)

In [28]:
x_train,x_test,y_train,y_test=train_test_split(tit_df.drop('Survived',axis=1),tit_df.Survived,random_state=101,test_size=0.2)

In [29]:
tit_gb=GaussianNB()

In [30]:
tit_gb.fit(x_train,y_train)

GaussianNB()

In [31]:
y_pred=tit_gb.predict(x_test)

In [32]:
accuracy_score(y_pred,y_test)

1.0

In [33]:
confusion_matrix(y_pred,y_test)

array([[47,  0],
       [ 0, 37]])